name       : nvidia-container-toolkit
version    : 1.0.5
release    : 1
source     :
    - https://github.com/NVIDIA/nvidia-container-runtime/archive/v3.1.4.tar.gz : 32bd9f49a1392253dccbfebc850b980b6d7cbd1b2621b06ced4fbe952c918038
license    : BSD-3-Clause
component  : programming.tools
summary    : NVIDIA Container Toolkit
description:
    The NVIDIA Container Toolkit allows users to build and run GPU accelerated Docker containers.
builddeps  :
    - golang
rundeps    :
    - libnvidia-container
replaces   :
    - nvidia-container-runtime
    - nvidia-docker
environment: |
    export GOPATH=$workdir
setup      : |
    %patch -p1 < $pkgfiles/support-stateless-configuration.patch
build      : |
    mkdir -p src
    ln -s $workdir/toolkit/nvidia-container-toolkit src
    go get -ldflags "-s -w" -v nvidia-container-toolkit
install    : |
    install -Dm00755 $GOPATH/bin/nvidia-container-toolkit $installdir/usr/bin/nvidia-container-toolkit
    ln -sv nvidia-container-toolkit $installdir/usr/bin/nvidia-container-runtime-hook
    install -Dm00644 toolkit/config.toml.centos $installdir/usr/share/nvidia-container-toolkit/config.toml
