name       : nvidia-container-toolkit
version    : 1.4.0
release    : 2
source     :
    - https://github.com/NVIDIA/nvidia-container-toolkit/archive/v1.4.0.tar.gz : a61ed73decb9233d3ed4d38fc420a8bb1eebaaae46ec8885cf8f556c607efc7a
license    : Apache-2.0
component  : programming.tools
networking : yes
summary    : NVIDIA Container Toolkit
description: |
    The NVIDIA Container Toolkit allows users to build and run GPU accelerated Docker containers.
builddeps  :
    - golang
rundeps    :
    - libnvidia-container
setup      : |
    %patch -p1 < $pkgfiles/support-stateless-configuration.patch
build      : |
    go build -ldflags "-s -w" -o bin/nvidia-container-toolkit ./pkg
install    : |
    install -Dm00755 bin/nvidia-container-toolkit $installdir/usr/bin/nvidia-container-toolkit
    ln -sv nvidia-container-toolkit $installdir/usr/bin/nvidia-container-runtime-hook
    install -Dm00644 config/config.toml.centos $installdir/usr/share/nvidia-container-runtime/config.toml
    install -Dm00644 oci-nvidia-hook.json $installdir/usr/share/containers/oci/hooks.d/00-oci-nvidia-hook.json
