name       : nvidia-container-toolkit
version    : 1.5.1
release    : 4
source     :
    - https://github.com/NVIDIA/nvidia-container-toolkit/archive/refs/tags/v1.5.1.tar.gz : 51d6f2fa0e740d7581f6c632875bb87bafc2351ba32830df11bb7cb19d87b763
license    : Apache-2.0
component  : programming.tools
networking : yes
summary    : NVIDIA Container Toolkit
description: |
    The NVIDIA Container Toolkit allows users to build and run GPU accelerated Docker containers.
builddeps  :
    - golang
rundeps    :
    - libnvidia-container
setup      : |
    %patch -p1 < $pkgfiles/support-stateless-configuration.patch
    %patch -p1 < $pkgfiles/fix_cgroups.patch
build      : |
    %make binary
install    : |
    install -Dm00755 nvidia-container-toolkit $installdir/usr/bin/nvidia-container-toolkit
    ln -sv nvidia-container-toolkit $installdir/usr/bin/nvidia-container-runtime-hook
    install -Dm00644 config/config.toml.centos $installdir/usr/share/nvidia-container-runtime/config.toml
    install -Dm00644 oci-nvidia-hook.json $installdir/usr/share/containers/oci/hooks.d/00-oci-nvidia-hook.json
